#Numeric Python - NumPy

In [1]:
import array

array = [1,2,3]

array*2 #(duplica o array)

[1, 2, 3, 1, 2, 3]

In [3]:
%pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 244.7 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 1.3 MB/s eta 0:00:0000:0100:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
array = np.array([1,2,3,4,5])

array*2 #multiplica cada elemento

array([ 2,  4,  6,  8, 10])

In [7]:
matriz = np.array([[1,2,3],[4,5,6]]) #2D

matriz*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

##Tensores

Matrizes que têm profundidade, como imagens (pixels < -largura, altura, saturação)

In [13]:
tensor = np.array([ #3D
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]
])

tensor*2

array([[[ 2,  4],
        [ 6,  8]],

       [[10, 12],
        [14, 16]],

       [[18, 20],
        [22, 24]]])

In [20]:
print(f'Minha matriz {matriz} é do tipo')
print(matriz.shape)
print(matriz.dtype)

print(f'Meu tensor {tensor} é do tipo')
print(tensor.shape)
print(tensor.dtype)

Minha matriz [[1 2 3]
 [4 5 6]] é do tipo
(2, 3)
int64
Meu tensor [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] é do tipo
(3, 2, 2)
int64
