# Numeric Python - NumPy

## Arrays

In [1]:
import array

array = [1,2,3]

array*2 #(duplica o array)

[1, 2, 3, 1, 2, 3]

In [3]:
%pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 244.7 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 1.3 MB/s eta 0:00:0000:0100:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
array = np.array([1,2,3,4,5])

array*2 #multiplica cada elemento

array([ 2,  4,  6,  8, 10])

In [7]:
matriz = np.array([[1,2,3],[4,5,6]]) #2D

matriz*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

##Tensores

Matrizes que têm profundidade, como imagens (pixels < -largura, altura, saturação)

In [13]:
tensor = np.array([ #3D
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]
])

tensor*2

array([[[ 2,  4],
        [ 6,  8]],

       [[10, 12],
        [14, 16]],

       [[18, 20],
        [22, 24]]])

In [20]:
print(f'Minha matriz {matriz} é do tipo')
print(matriz.shape)
print(matriz.dtype)

print(f'Meu tensor {tensor} é do tipo')
print(tensor.shape)
print(tensor.dtype)

Minha matriz [[1 2 3]
 [4 5 6]] é do tipo
(2, 3)
int64
Meu tensor [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] é do tipo
(3, 2, 2)
int64


In [26]:
tensor_zeros = np.zeros((2,3,3))
print(tensor_zeros)
print(type(tensor_zeros))

matriz_zeros = np.zeros((2,3))
print(matriz_zeros)
print(type(matriz_zeros))


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
<class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [38]:
random = np.random.rand(5,7) #FLOAT random numbers between [0, 1]

print(random)

[[0.72525387 0.99033124 0.98592811 0.50151355 0.66603465 0.87559492
  0.65885219]
 [0.66091099 0.04163922 0.09352269 0.92494126 0.62976103 0.82800174
  0.29616311]
 [0.35935148 0.23488291 0.77277377 0.82204951 0.5234326  0.25265804
  0.63567427]
 [0.55238034 0.73385926 0.55683574 0.12831975 0.85712939 0.77612363
  0.03412958]
 [0.05365287 0.06045218 0.1792788  0.3025682  0.42767043 0.28099364
  0.41580857]]


In [39]:
random_int = np.random.randint(0,20, size=(3,3))

print(random_int)

[[16 12 17]
 [ 0  7 15]
 [ 9 12  2]]


Crie um array numpy com 10 elementos inteiros aleatórios no intervalo [0,100] e exiba os valores e tipo do array

In [40]:
array_exercicio = np.random.randint(0,100,size=(10))

print(array_exercicio)
print(type(array_exercicio))

[85 38 19  5 37 61 16 19 19 82]
<class 'numpy.ndarray'>


In [48]:
array_exercicio = np.random.randint(0,100,10)

print(array_exercicio)
print(type(array_exercicio))

[22 88 98 75  4 49 49 23 43  4]
<class 'numpy.ndarray'>


In [49]:
lista = [1,2,3,4,5]

lista[0]

1

In [64]:
my_array = np.array([[1,2,3],[4,5,6]])

my_array[0][1]

2

In [65]:
my_array[-1][-1]

6

In [66]:
my_array[-1][0]

4

In [69]:
print(my_array)
print()
print(my_array[0:2,1:3])

[[1 2 3]
 [4 5 6]]

[[2 3]
 [5 6]]


In [70]:
print(my_array[1,:])

[4 5 6]
